### PR TITLE
fix: upgrade the test framework form monkey to mockey (#431)

### LINKED ISSUE #431: Testing: Upgrade the unit test framework
### What would you like to be added?

I'd like to upgrade the UT monkey framework from bou.ke/monkey to bytedance/mockey.

### Why is this needed?

Cause bou.ke/monkey does not support for MacOs/M1, and it's already archived.
image

I have already tried some popular go monkey repos, such as agiledragon/gomonkey, but they cannot support MacOs/M1. Thus, I choose bytedance/mockey.

### PR DESCRIPTION
**Pull request by Mrcopytuo**
#### What type of PR is this?

unit test

#### What this PR does / why we need it:

Upgrade the unit test framework to fit all platforms

#### Which issue(s) this PR fixes:

Fixes #431 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/cmd/ls/types_test.go [hunk 1]
```diff
@@ -27,12 +27,13 @@ var (
 )
 
 func Test_lsReport_Human(t *testing.T) {
-	defer monkey.UnpatchAll()
-	mockPromptOutput()
+	mockey.PatchConvey("test le report human", t, func() {
```
Comment (healthjyk) [inline pkg/cmd/ls/types_test.go:30]: “le" is not correct, change to "test lsReport human"

**Review by healthjyk — APPROVED** [review]
