### PR TITLE
fix: add workdir to meta flag of kusion cli

### LINKED ISSUE #1064: Bug: Support -w in kusion commands
### What would you like to be added?

Support `-w` in kusion commands like 'apply', 'preview', 'destroy', etc to specify the current work directory

### Why is this needed?

Revert breaking changes

### PR DESCRIPTION
**Pull request by liu-hm19**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
This PR adds `--workdir` to meta flags of Kusion CLI. 
#### Which issue(s) this PR fixes:

Fixes #1064 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/cmd/meta/meta.go [hunk 1]
```diff
@@ -67,14 +71,25 @@ func (f *MetaFlags) AddFlags(cmd *cobra.Command) {
 	if f.Backend != nil {
 		cmd.Flags().StringVarP(f.Backend, "backend", "", *f.Backend, i18n.T("The backend to use, supports 'local', 'oss' and 's3'."))
 	}
+	if f.WorkDir != nil {
+		cmd.Flags().StringVarP(f.WorkDir, "workdir", "", *f.WorkDir, i18n.T("The work directory to run Kusion CLI."))
```
Comment (SparkYuan) [inline pkg/cmd/meta/meta.go:75]: add a shorthand for this flag

**Review by adohe — APPROVED** [review]
/lgtm
