### PR TITLE
fix: delete external templates when init --online failed

### LINKED ISSUE #368: kusion init --online failed
### What happened?

When I use kusion init --online, an error “cloning templates repos: reference not found". Is it the problem of directory?
image

### What did you expect to happen?

Fix it

### How can we reproduce it (as minimally and precisely as possible)?

run kusion init --online

### Anything else we need to know?

_No response_

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>
v0.8.1

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### PR DESCRIPTION
**Pull request by SparkYuan**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
always delete external templates in init with the online flag
#### Which issue(s) this PR fixes:

Fixes #368

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scaffold/templates.go [hunk 1]
```diff
@@ -192,23 +191,23 @@ func retrieveFileTemplates(path string) (TemplateRepository, error) {
...
 	templateDir, err := GetTemplateDir(ExternalTemplateDir)
 	if err != nil {
 		return TemplateRepository{}, err
 	}
 
+	// delete old external templates
+	if err = os.RemoveAll(templateDir); err != nil {
+		return TemplateRepository{}, err
+	}
+
```
Comment (healthjyk) [inline pkg/scaffold/templates.go:208]: It seems that removing repos if git clone failed is much better, add a `defer` after line 218.
Besides, why using pulumi to git clone, it's such a basic function. Use a third-party package may cause unnecessary dependency problems.

File: pkg/scaffold/templates.go [hunk 2]
```diff
@@ -351,15 +314,15 @@ var (
...
 	}
 
 	if len(s) > 100 {
-		return errors.New("A project name must be 100 characters or less")
+		return errors.New("a project name must be 100 characters or less")
 	}
 
 	if !validProjectNameRegexp.MatchString(s) {
-		return errors.New("A project name may only contain alphanumeric, hyphens, underscores, and periods")
+		return errors.New("a project name may only contain alphanumeric, hyphens, underscores, and periods")
```
Comment (healthjyk) [inline pkg/scaffold/templates.go:325]: not "may", but "must".

File: pkg/scaffold/templates.go [hunk 3]
```diff
@@ -351,15 +314,15 @@ var (
 // for display to an end user.
 func ValidateProjectName(s string) error {
 	if s == "" {
-		return errors.New("A project name may not be empty")
+		return errors.New("a project name may not be empty")
```
Comment (healthjyk) [inline pkg/scaffold/templates.go:317]: not "may", but "must".
delete "a" is better, or "a project's name", the same for the below.

File: pkg/scaffold/templates.go [hunk 4]
```diff
@@ -351,15 +314,15 @@ var (
...
 	}
 
 	if len(s) > 100 {
-		return errors.New("A project name must be 100 characters or less")
+		return errors.New("a project name must be 100 characters or less")
```
Comment (healthjyk) [inline pkg/scaffold/templates.go:321]: "must be equal or less than 100 characters“ is better

File: pkg/scaffold/templates.go (hunk 1 above)
Comment (SparkYuan) [reply pkg/scaffold/templates.go]: Are you intending to add `defer` with `recover` in this function? It will catch all errors and we have to distinguish which one is a git error.I moved the logic to #L215. The template directory will only be removed if the git clone fails.

File: pkg/scaffold/templates.go [hunk 5]
```diff
@@ -192,33 +191,31 @@ func retrieveFileTemplates(path string) (TemplateRepository, error) {
...
 
 	if online {
 		// Clone or update the kusion/templates repo.
 		repo := KusionTemplateGitRepository
 		branch := plumbing.NewBranchReferenceName(kusionTemplateBranch)
-		err := gitutil.GitCloneOrPull(repo, branch, templateDir, false /*shallow*/)
+		err = gitutil.GitCloneOrPull(repo, branch, templateDir, false /*shallow*/)
 		if err != nil {
-			return TemplateRepository{}, fmt.Errorf("cloning templates repo: %w", err)
+			if err2 := os.RemoveAll(templateDir); err2 != nil {
```
Comment (healthjyk) [inline pkg/scaffold/templates.go:215]: maybe removeErr is better.

**Comment by healthjyk** [comment]
please upgrade the title

**Review by healthjyk — APPROVED** [review]
