### PR TITLE
fix: compile error with -w flag in kpm mode

### LINKED ISSUE #537: bug: apply failed with -w flag
### What happened?

image

### What did you expect to happen?

Apply success

### How can we reproduce it (as minimally and precisely as possible)?

execute `kusion apply -w ${your work dir}`

### Anything else we need to know?

_No response_

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### PR DESCRIPTION
**Pull request by SparkYuan**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix compile error with -w flag in kpm mode
#### Which issue(s) this PR fixes:

Fixes #537 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/generator/kcl/kcl_generator.go [hunk 1]
```diff
@@ -72,9 +73,11 @@ func Run(o *generator.Options, stack *projectstack.Stack) (*CompileResult, error
 
 	var result *kcl.KCLResultList
 	if o.IsKclPkg {
-		result, err = api.RunCurrentPkg(&opt.CompileOptions{
+		opts := &opt.CompileOptions{
 			Option: kclpkg.NewOption().Merge(optList...),
-		})
+		}
+		opts.SetPkgPath(o.WorkDir)
```
Comment (elliotxx) [inline pkg/generator/kcl/kcl_generator.go:79]: The options include `workDir`, and I understand that there is no need to assign `workDir` to `pkgPath` separately.
@zong-zhe

**Review by elliotxx — APPROVED** [review]
lgtm
